### ISSUE TITLE
Android 14: `Process com.android.phone isn't responding`

### ISSUE THREAD

**Issue by StupidRepo** [TrebleDroid/platform_frameworks_opt_telephony#2]
`com.android.phone` stops responding, leaving my SIM card in an unusable state and making apps think there isn't a SIM card inserted when there is. Also breaks Settings and a whole bunch of other stuff. Please read https://github.com/TrebleDroid/treble_experimentations/issues/96, and https://github.com/phhusson/treble_experimentations/issues/2617 (this is my issue report but as I put it on the wrong repo, I closed it. please still read it anyway)

**Comment by phhusson** [comment]
This is not the right place to discuss this, TrebleDroid/treble_experimentations is the right place.

**Comment by b1bradders** [comment]
Well, hold on, the description to this repo says the following:

```
These libraries run in the com.android.phone process and exist to support
telephony services created by the user’s apps.
```

These libraries may be what are making `com.android.phone` crash, no? Therefore, this could be the correct place as these libraries may be crashing `com.android.phone`.

**Comment by b1bradders** [comment]
@phhusson And also, this seems very much related to this repository and should be the right place to discuss this, due to the fact that this looks as though it holds the stuff for com.android.phone, or am I wrong?

**Comment by phhusson** [comment]
It could be those libraries, or it could be packages/services/telephony, or packages/services/telecomm, or probably a dozen others.

**Comment by b1bradders** [comment]
Hm, okay. Well, are you going to look at https://github.com/TrebleDroid/treble_experimentations/issues/96 and https://github.com/phhusson/treble_experimentations/issues/2617 soon? Receiving SMS and such is crucial if I want to access services like GitHub on another computer where I don't have my backup codes.
